# Generated by Django 5.0 on 2024-02-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
