# Generated by Django 5.0 on 2024-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_bio_alter_customuser_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cv',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
